name: Rust

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop, release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --no-fail-fast
    - name: Run fmt tests
      run: cargo fmt -- --check
