name: Rust

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop, release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run fmt tests
      run: cargo fmt -- --check
<<<<<<< Updated upstream
    - name: Test with default features
      run: cargo test --no-fail-fast
    - name: Test with most features
      run: cargo test --no-fail-fast --no-default-features --features faithful,raw_headers,query_strings,extended_queries,cookies,url_variables,rustls
    - name: Test with openSSL
      run: cargo test --no-fail-fast --features openSSL
    - name: Test with no features
      run: cargo test --no-fail-fast --no-default-features
=======
    - name: Build with rustls
      run: cargo build --verbose --features rustls
    - name: Build with openSSL
      run: cargo build --verbose --features openSSL
    - name: Build with no-default-features
      run: cargo build --verbose --no-default-features
>>>>>>> Stashed changes
